### ISSUE TITLE
Jio tv not working 

### ISSUE THREAD

**Issue by chintamani13** [mitthu786/TS-JioTV#28]
Jio tv not working Android tv

**Comment by shmbub2** [comment]
Use this m3u, it works

https://bit.ly/Jio_m3u8

**Comment by Ursgirishgupta** [comment]
> Use this m3u, it works
> 
> https://bit.ly/Jio_m3u8

@shmbub2  it also not working please share the updated one.

**Comment by shmbub2** [comment]
Ryt, i am also getting error
