### ISSUE TITLE
Not working l

### ISSUE THREAD

**Issue by SaifiTech-Developers** [mitthu786/TS-JioTV#46]
![Screenshot_20230906-153336](https://github.com/mitthu786/TS-JioTV/assets/137592124/bebd8ed6-1214-4c41-b168-a45ac9b94f62)
Not working bro

**Comment by VenomDino** [comment]
because jio has blocked your server ip address

**Comment by SaifiTech-Developers** [comment]
Please provide worldwide php script

**Comment by SaifiTech-Developers** [comment]
Or it's alternative
