### ISSUE TITLE
Tataplay 

### ISSUE THREAD

**Issue by GUR1322** [mitthu786/TS-JioTV#53]
Hello bro how i can make tataplay catch-up? Please contact with me give me your contact telegram username your link not working 

Please contact with me

**Comment by mitthu786** [comment]
Soon for Public 🙂

**Comment by GUR1322** [comment]
> Soon for Public 🙂

**Comment by GUR1322** [comment]
Bhai me apke discussion group se ban hu ye kyu ? Mene kabhi apka group join bi nhi kiya
Please contact with me https://telegram.me/@Garryworld_bot
