### ISSUE TITLE
Parse error: syntax error, unexpected end of file in /storage/emulated/0/htdocs/TS-JioTV/app/details.php on line 253

### ISSUE THREAD

**Issue by Gautam-Pra** [mitthu786/TS-JioTV#56]
Please solve this error!

Parse error: syntax error, unexpected end of file in /storage/emulated/0/htdocs/TS-JioTV/app/details.php on line 253

![IMG_20240210_193759](https://github.com/mitthu786/TS-JioTV/assets/84336961/41b9d842-377e-40ab-b7b8-e0e650da6122)

![IMG_20240210_193810](https://github.com/mitthu786/TS-JioTV/assets/84336961/bdafde0b-57da-408b-abce-7dbf41b16205)

**Comment by mitthu786** [comment]
UPDATE YOUR KSWEB PRO
